'use strict';
const K={url:'egpHub.scriptUrl',key:'egpHub.accessKey',cache:'egpHub.cache',refresh:'egpHub.refresh'};
const I={down:'assets/icons/chevron-down-svgrepo-com.svg',right:'assets/icons/chevron-right-svgrepo-com.svg',copy:'assets/icons/copy-svgrepo-com.svg',edit:'assets/icons/edit-3-svgrepo-com.svg',trash:'assets/icons/trash-xmark-svgrepo-com.svg'};
const P={Critical:0,High:1,Medium:2,Low:3};
const S={entries:[],open:new Set(),openF:new Set(),editing:null,copy:null,loading:false,timer:null,presentation:false};
const $=id=>document.getElementById(id); const E={list:$('questionList'),empty:$('emptyState'),loading:$('loadingState'),qCount:$('questionCount'),fCount:$('followupCount'),cCount:$('criticalCount'),hCount:$('highCount'),last:$('lastSyncedText'),status:$('syncStatus'),statusText:$('syncStatusText'),search:$('searchInput'),cat:$('categoryFilter'),pri:$('priorityFilter'),sort:$('sortSelect'),qDialog:$('questionDialog'),qForm:$('questionForm'),title:$('questionDialogTitle'),question:$('questionField'),answer:$('answerField'),category:$('categoryField'),priority:$('priorityField'),tags:$('tagsField'),notes:$('notesField'),fFields:$('followupFields'),save:$('saveQuestionBtn'),settings:$('settingsDialog'),settingsForm:$('settingsForm'),url:$('scriptUrlField'),key:$('accessKeyField'),refresh:$('autoRefreshField'),copyDialog:$('copyDialog'),toast:$('toast')};
function uid(){return crypto.randomUUID?crypto.randomUUID():`egp-${Date.now()}-${Math.random().toString(16).slice(2)}`}
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function parse(v){try{const x=typeof v==='string'?JSON.parse(v||'[]'):v;return Array.isArray(x)?x:[]}catch{return[]}}
function norm(r){return{id:String(r.id||r.ID||''),question:String(r.question||r.Question||'').trim(),answer:String(r.answer||r.Answer||'').trim(),category:String(r.category||r.Category||'General').trim()||'General',priority:String(r.priority||r.Priority||'Medium'),tags:String(r.tags||r.Tags||''),notes:String(r.notes||r.Notes||''),followups:parse(r.followups||r.FollowUps_JSON).map(f=>({id:String(f.id||uid()),question:String(f.question||'').trim(),answer:String(f.answer||'').trim()})).filter(f=>f.question||f.answer),createdAt:String(r.createdAt||r.CreatedAt||''),updatedAt:String(r.updatedAt||r.UpdatedAt||'')}}
function conn(){return{url:(localStorage.getItem(K.url)||'').trim(),key:(localStorage.getItem(K.key)||'').trim()}}
function connected(){const c=conn();return !!(c.url&&c.key)}
function cache(){localStorage.setItem(K.cache,JSON.stringify(S.entries))} function loadCache(){try{return JSON.parse(localStorage.getItem(K.cache)||'[]').map(norm)}catch{return[]}}
function status(mode,text){E.status.className=`sync-status ${mode}`;E.statusText.textContent=text}
function toast(t){E.toast.textContent=t;E.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>E.toast.classList.remove('show'),2400)}
async function api(action,payload={}){const c=conn();if(!c.url||!c.key)throw Error('Connect Google Sheets first.');const r=await fetch(c.url,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,key:c.key,...payload})});const j=await r.json();if(!j.ok)throw Error(j.error||'Request failed');return j}
async function sync({quiet=false}={}){if(!connected()){S.entries=loadCache();status('setup','Setup required');render();return}S.loading=true;status('saving','Fetching...');render();try{const r=await api('list');S.entries=(r.data||[]).map(norm).filter(x=>x.id&&x.question);cache();status('synced','Autosaved & synced');E.last.textContent=new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});if(!quiet)toast('Latest Sheet data loaded.')}catch(e){S.entries=loadCache();status('error','Offline · cached copy');if(!quiet)toast(e.message)}finally{S.loading=false;render()}}
function filtered(){const q=E.search.value.toLowerCase().trim(),cat=E.cat.value,pri=E.pri.value;let a=S.entries.filter(x=>(cat==='all'||x.category===cat)&&(pri==='all'||x.priority===pri)).filter(x=>!q||[x.question,x.answer,x.category,x.priority,x.tags,x.notes,...x.followups.flatMap(f=>[f.question,f.answer])].join(' ').toLowerCase().includes(q));const sort=E.sort.value;return a.sort((x,y)=>sort==='priority'?(P[x.priority]??9)-(P[y.priority]??9)||(x.question.localeCompare(y.question)):sort==='updated'?(Date.parse(y.updatedAt)||0)-(Date.parse(x.updatedAt)||0):sort==='created'?(Date.parse(y.createdAt)||0)-(Date.parse(x.createdAt)||0):sort==='alphabetical'?x.question.localeCompare(y.question):sort==='category'?x.category.localeCompare(y.category)||x.question.localeCompare(y.question):y.followups.length-x.followups.length)}
function filters(){const current=E.cat.value;const cats=[...new Set(S.entries.map(x=>x.category))].sort();E.cat.innerHTML='<option value="all">All categories</option>'+cats.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if([...E.cat.options].some(o=>o.value===current))E.cat.value=current}
function render(){filters();E.qCount.textContent=S.entries.length;E.fCount.textContent=S.entries.reduce((n,x)=>n+x.followups.length,0);E.cCount.textContent=S.entries.filter(x=>x.priority==='Critical').length;E.hCount.textContent=S.entries.filter(x=>x.priority==='High').length;E.loading.classList.toggle('hidden',!S.loading);if(S.loading){E.list.innerHTML='';return}const a=filtered();E.empty.classList.toggle('hidden',a.length>0);E.list.innerHTML=a.map(card).join('');bind()}
function card(x){const open=S.open.has(x.id);return `<article class="question-card ${open?'open':''}" data-entry-id="${esc(x.id)}"><div class="question-row"><button class="question-toggle" data-tq="${esc(x.id)}"><img class="chevron" src="${open?I.down:I.right}" alt=""><span class="priority-badge p-${x.priority.toLowerCase()}">${esc(x.priority)}</span><span class="question-meta"><span class="category-label">${esc(x.category)}</span><span class="question-title">${esc(x.question)}</span></span></button><div class="card-actions"><button class="card-icon-button" data-copy="${esc(x.id)}"><img src="${I.copy}" alt="Copy"></button><button class="card-icon-button" data-edit="${esc(x.id)}"><img src="${I.edit}" alt="Edit"></button><button class="card-icon-button danger" data-delete="${esc(x.id)}"><img src="${I.trash}" alt="Delete"></button></div></div><div class="question-content"><div class="question-content-inner"><div class="question-body"><div class="answer-box"><p class="answer-label">Answer</p><p class="answer-text">${esc(x.answer)}</p></div>${x.tags?`<div class="tag-row">${x.tags.split(',').filter(Boolean).map(t=>`<span>${esc(t.trim())}</span>`).join('')}</div>`:''}${x.notes&&!S.presentation?`<div class="notes-box"><b>Internal notes</b><p>${esc(x.notes)}</p></div>`:''}${x.followups.length?`<div class="followups-block"><div class="followups-heading"><h4>Follow-up questions</h4><span>${x.followups.length}</span></div><div class="followup-list">${x.followups.map(f=>follow(x.id,f)).join('')}</div></div>`:''}<div class="updated-line">Updated ${fmt(x.updatedAt||x.createdAt)}</div></div></div></div></article>`}
function follow(id,f){const k=`${id}:${f.id}`,o=S.openF.has(k);return `<article class="followup-item ${o?'open':''}"><button class="followup-question" data-tf="${esc(k)}"><img src="${o?I.down:I.right}" alt=""><span>${esc(f.question||'Untitled follow-up')}</span></button><div class="followup-answer"><div><p>${esc(f.answer||'No answer yet.')}</p></div></div></article>`}
function fmt(d){const x=new Date(d);return isNaN(x)?'—':x.toLocaleDateString()}
function bind(){document.querySelectorAll('[data-tq]').forEach(b=>b.onclick=()=>{const id=b.dataset.tq;S.open.has(id)?S.open.delete(id):S.open.add(id);render()});document.querySelectorAll('[data-tf]').forEach(b=>b.onclick=()=>{const k=b.dataset.tf;S.openF.has(k)?S.openF.delete(k):S.openF.add(k);render()});document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>{S.copy=b.dataset.copy;E.copyDialog.showModal()});document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>del(b.dataset.delete))}
function newQ(){S.editing=null;E.qForm.reset();E.title.textContent='New Question';E.priority.value='High';E.fFields.innerHTML='';addF();E.qDialog.showModal();setTimeout(()=>E.question.focus(),30)}
function edit(id){const x=S.entries.find(e=>e.id===id);if(!x)return;S.editing=id;E.title.textContent='Edit Question';E.question.value=x.question;E.answer.value=x.answer;E.category.value=x.category;E.priority.value=x.priority;E.tags.value=x.tags;E.notes.value=x.notes;E.fFields.innerHTML='';(x.followups.length?x.followups:[{}]).forEach(f=>addF(f.question,f.answer,f.id));E.qDialog.showModal()}
function addF(q='',a='',id=''){const d=document.createElement('div');d.className='followup-field';d.dataset.id=id||uid();d.innerHTML=`<textarea class="followup-question-field" placeholder="Follow-up question">${esc(q)}</textarea><textarea class="followup-answer-field" placeholder="Prepared answer">${esc(a)}</textarea><button class="remove-followup" type="button">×</button>`;d.querySelector('button').onclick=()=>d.remove();E.fFields.appendChild(d)}
async function save(ev){ev.preventDefault();const old=S.entries.find(x=>x.id===S.editing),now=new Date().toISOString();const entry={id:old?.id||uid(),question:E.question.value.trim(),answer:E.answer.value.trim(),category:E.category.value.trim()||'General',priority:E.priority.value,tags:E.tags.value.trim(),notes:E.notes.value.trim(),followups:[...E.fFields.children].map(d=>({id:d.dataset.id,question:d.querySelector('.followup-question-field').value.trim(),answer:d.querySelector('.followup-answer-field').value.trim()})).filter(f=>f.question||f.answer),createdAt:old?.createdAt||now,updatedAt:now};try{status('saving','Saving...');E.save.disabled=true;await api('upsert',{entry});E.qDialog.close();await sync({quiet:true});status('synced','Autosaved & synced');toast(old?'Question updated everywhere.':'Question added everywhere.')}catch(e){status('error','Save failed');toast(e.message)}finally{E.save.disabled=false}}
async function del(id){const x=S.entries.find(e=>e.id===id);if(!x||!confirm(`Delete “${x.question}” everywhere?`))return;try{status('saving','Deleting...');await api('delete',{id});await sync({quiet:true});toast('Question deleted everywhere.')}catch(e){status('error','Delete failed');toast(e.message)}}
async function copy(mode){const x=S.entries.find(e=>e.id===S.copy);if(!x)return;let t=x.answer;if(mode==='qa')t=`${x.question}\n\n${x.answer}`;if(mode==='thread')t=`${x.question}\n\n${x.answer}`+x.followups.map((f,i)=>`\n\nFollow-up ${i+1}: ${f.question}\n${f.answer}`).join('');try{await navigator.clipboard.writeText(t)}catch{const a=document.createElement('textarea');a.value=t;document.body.append(a);a.select();document.execCommand('copy');a.remove()}E.copyDialog.close();toast('Copied.')}
function openSettings(){const c=conn();E.url.value=c.url;E.key.value=c.key;E.refresh.value=localStorage.getItem(K.refresh)||'60';E.settings.showModal()}
function schedule(){clearInterval(S.timer);const sec=Number(localStorage.getItem(K.refresh)||60);if(sec>0)S.timer=setInterval(()=>{if(!document.hidden)sync({quiet:true})},sec*1000)}
async function saveSettings(ev){ev.preventDefault();localStorage.setItem(K.url,E.url.value.trim());localStorage.setItem(K.key,E.key.value.trim());localStorage.setItem(K.refresh,E.refresh.value);E.settings.close();schedule();await sync()}
function disconnect(){localStorage.removeItem(K.url);localStorage.removeItem(K.key);E.settings.close();S.entries=loadCache();status('setup','Setup required');render()}
$('newQuestionBtn').onclick=newQ;$('refreshBtn').onclick=()=>sync();$('settingsBtn').onclick=openSettings;$('addFollowupBtn').onclick=()=>addF();$('disconnectBtn').onclick=disconnect;$('presentationBtn').onclick=()=>{S.presentation=!S.presentation;document.body.classList.toggle('presentation',S.presentation);$('presentationBtn').textContent=S.presentation?'Exit Presentation':'Presentation';render()};E.qForm.onsubmit=save;E.settingsForm.onsubmit=saveSettings;[E.search,E.cat,E.pri,E.sort].forEach(x=>x.addEventListener(x.tagName==='INPUT'?'input':'change',render));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());document.querySelectorAll('[data-copy-mode]').forEach(b=>b.onclick=()=>copy(b.dataset.copyMode));document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();E.search.focus()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='n'){e.preventDefault();newQ()}if(e.key==='Escape')document.querySelectorAll('dialog[open]').forEach(d=>d.close())});S.entries=loadCache();render();schedule();sync({quiet:true});
